name: ctypeslib-linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # python-version: [ 3.5, 3.6, 3.7, 3.8, 3.9 ]
         os: [ubuntu-latest]
         python-version: [ 3.9 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Clang
      uses: egor-tensin/setup-clang@v1
      with:
        platform: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install clang coveralls
    - name: build test libs
      run: |
        CFLAGS="-Wall -Wextra -Werror -std=c99 -pedantic -fpic"
        LDFLAGS="-shared"
        clang $CFLAGS $LDFLAGS -o test/data/test-callbacks.so test/data/test-callbacks.c
    - name: Install clang2py
      run: |
        python setup.py develop
    - name: Test with Unittest and coverage
      run: |
        coverage run --source=ctypeslib setup.py test
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}